import { Roboto } from "next/font/google";
import Header from "../components/layout/Header.js";
import "./globals.css";
import {AppProvider} from "@/components/AppContext.js";
import {Toaster} from "react-hot-toast";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={roboto.className}>
        <main className="max-w-6xl mx-auto p-4">
          <AppProvider>
            <Toaster/>
            <Header />
            {children}
            <footer className="text-center border-t mt-12 p-8">
              &copy; 2024 Étterem
            </footer>
          </AppProvider>
        </main>
      </body>
    </html>
  );
}
